### ISSUE TITLE
why the apk have 151.8 M size ?

### ISSUE THREAD

**Issue by wwdok** [djh123/yolov5Android#1]
I am curious about where is the big part

**Comment by wwdok** [comment]
well, i know now, it is because the bin and param in the assets folder take up most of the space.
From the picture, it seeems this app take image as input, not video ?
![image](https://user-images.githubusercontent.com/43233772/98613259-e4440f00-2330-11eb-8ef2-e61857268b6d.png)

**Comment by djh123** [comment]
model size 30M
opencv so size 18M
ncnn lib .a size 7M

in assert directory  you can delete same model。maybe ！！it‘s my fault。

and then 

must  to be optimize the,model net and opencv so.

**Comment by djh123** [comment]
you can use https://github.com/djh123/doc_Detection this project make camera yuv data。video is also image frame。

**Comment by wwdok** [comment]
@djh123 Got it, thanks !
